<?php
function cyr_to_url($cyrstr) // Перекодирование кирилицы в формат UTF-8
{
	$cyrstr = str_replace(" ", "%20", $cyrstr);
	$cyrstr = str_replace("А", "%D0%90", $cyrstr);
	$cyrstr = str_replace("Б", "%D0%91", $cyrstr);
	$cyrstr = str_replace("В", "%D0%92", $cyrstr);
	$cyrstr = str_replace("Г", "%D0%93", $cyrstr);
	$cyrstr = str_replace("Д", "%D0%94", $cyrstr);
	$cyrstr = str_replace("Е", "%D0%A3", $cyrstr);
	$cyrstr = str_replace("Ё", "%D0%81", $cyrstr);
	$cyrstr = str_replace("Ж", "%D0%96", $cyrstr);
	$cyrstr = str_replace("З", "%D0%97", $cyrstr);
	$cyrstr = str_replace("И", "%D0%98", $cyrstr);
	$cyrstr = str_replace("Й", "%D0%99", $cyrstr);
	$cyrstr = str_replace("К", "%D0%9A", $cyrstr);
	$cyrstr = str_replace("Л", "%D0%9B", $cyrstr);
	$cyrstr = str_replace("М", "%D0%9C", $cyrstr);
	$cyrstr = str_replace("Н", "%D0%9D", $cyrstr);
	$cyrstr = str_replace("О", "%D0%9E", $cyrstr);
	$cyrstr = str_replace("П", "%D0%9F", $cyrstr);
	$cyrstr = str_replace("Р", "%D0%A0", $cyrstr);
	$cyrstr = str_replace("С", "%D0%A1", $cyrstr);
	$cyrstr = str_replace("Т", "%D0%A2", $cyrstr);
	$cyrstr = str_replace("У", "%D0%A3", $cyrstr);
	$cyrstr = str_replace("Ф", "%D0%A4", $cyrstr);
	$cyrstr = str_replace("Х", "%D0%A5", $cyrstr);
	$cyrstr = str_replace("Ц", "%D0%A6", $cyrstr);
	$cyrstr = str_replace("Ч", "%D0%A7", $cyrstr);
	$cyrstr = str_replace("Ш", "%D0%A8", $cyrstr);
	$cyrstr = str_replace("Щ", "%D0%A9", $cyrstr);
	$cyrstr = str_replace("Ь", "%D0%AC", $cyrstr);
	$cyrstr = str_replace("Ы", "%D0%AB", $cyrstr);
	$cyrstr = str_replace("Ъ", "%D0%AA", $cyrstr);
	$cyrstr = str_replace("Э", "%D0%AD", $cyrstr);
	$cyrstr = str_replace("Ю", "%D0%AE", $cyrstr);
	$cyrstr = str_replace("Я", "%D0%AF", $cyrstr);

	$cyrstr = str_replace("а", "%D0%B0", $cyrstr);
	$cyrstr = str_replace("б", "%D0%B1", $cyrstr);
	$cyrstr = str_replace("в", "%D0%B2", $cyrstr);
	$cyrstr = str_replace("г", "%D0%B3", $cyrstr);
	$cyrstr = str_replace("д", "%D0%B4", $cyrstr);
	$cyrstr = str_replace("е", "%D0%B5", $cyrstr);
	$cyrstr = str_replace("ё", "%D1%91", $cyrstr);
	$cyrstr = str_replace("ж", "%D0%B6", $cyrstr);
	$cyrstr = str_replace("з", "%D0%B7", $cyrstr);
	$cyrstr = str_replace("и", "%D0%B8", $cyrstr);
	$cyrstr = str_replace("й", "%D0%B9", $cyrstr);
	$cyrstr = str_replace("к", "%D0%BA", $cyrstr);
	$cyrstr = str_replace("л", "%D0%BB", $cyrstr);
	$cyrstr = str_replace("м", "%D0%BC", $cyrstr);
	$cyrstr = str_replace("н", "%D0%BD", $cyrstr);
	$cyrstr = str_replace("о", "%D0%BE", $cyrstr);
	$cyrstr = str_replace("п", "%D0%BF", $cyrstr);
	$cyrstr = str_replace("р", "%D1%80", $cyrstr);
	$cyrstr = str_replace("с", "%D1%81", $cyrstr);
	$cyrstr = str_replace("т", "%D1%82", $cyrstr);
	$cyrstr = str_replace("у", "%D1%83", $cyrstr);
	$cyrstr = str_replace("ф", "%D1%84", $cyrstr);
	$cyrstr = str_replace("х", "%D1%85", $cyrstr);
	$cyrstr = str_replace("ц", "%D1%86", $cyrstr);
	$cyrstr = str_replace("ч", "%D1%87", $cyrstr);
	$cyrstr = str_replace("ш", "%D1%88", $cyrstr);
	$cyrstr = str_replace("щ", "%D1%89", $cyrstr);
	$cyrstr = str_replace("ь", "%D1%8C", $cyrstr);
	$cyrstr = str_replace("ы", "%D1%8B", $cyrstr);
	$cyrstr = str_replace("ъ", "%D1%8A", $cyrstr);
	$cyrstr = str_replace("э", "%D1%8D", $cyrstr);
	$cyrstr = str_replace("ю", "%D1%8E", $cyrstr);
	$cyrstr = str_replace("я", "%D1%8F", $cyrstr);

	return $cyrstr;
}

function url_to_cyr($cyrstr) // Перекодирование кирилицы в формат UTF-8
{
	$cyrstr = str_replace("%20", " ", $cyrstr);
	$cyrstr = str_replace("%D0%90", "А", $cyrstr);
	$cyrstr = str_replace("%D0%91", "Б", $cyrstr);
	$cyrstr = str_replace("%D0%92", "В", $cyrstr);
	$cyrstr = str_replace("%D0%93", "Г", $cyrstr);
	$cyrstr = str_replace("%D0%94", "Д", $cyrstr);
	$cyrstr = str_replace("%D0%A3", "Е", $cyrstr);
	$cyrstr = str_replace("%D0%81", "Ё", $cyrstr);
	$cyrstr = str_replace("%D0%96", "Ж", $cyrstr);
	$cyrstr = str_replace("%D0%97", "З", $cyrstr);
	$cyrstr = str_replace("%D0%98", "И", $cyrstr);
	$cyrstr = str_replace("%D0%99", "Й", $cyrstr);
	$cyrstr = str_replace("%D0%9A", "К", $cyrstr);
	$cyrstr = str_replace("%D0%9B", "Л", $cyrstr);
	$cyrstr = str_replace("%D0%9C", "М", $cyrstr);
	$cyrstr = str_replace("%D0%9D", "Н", $cyrstr);
	$cyrstr = str_replace("%D0%9E", "О", $cyrstr);
	$cyrstr = str_replace("%D0%9F", "П", $cyrstr);
	$cyrstr = str_replace("%D0%A0", "Р", $cyrstr);
	$cyrstr = str_replace("%D0%A1", "С", $cyrstr);
	$cyrstr = str_replace("%D0%A2", "Т", $cyrstr);
	$cyrstr = str_replace("%D0%A3", "У", $cyrstr);
	$cyrstr = str_replace("%D0%A4", "Ф", $cyrstr);
	$cyrstr = str_replace("%D0%A5", "Х", $cyrstr);
	$cyrstr = str_replace("%D0%A6", "Ц", $cyrstr);
	$cyrstr = str_replace("%D0%A7", "Ч", $cyrstr);
	$cyrstr = str_replace("%D0%A8", "Ш", $cyrstr);
	$cyrstr = str_replace("%D0%A9", "Щ", $cyrstr);
	$cyrstr = str_replace("%D0%AC", "Ь", $cyrstr);
	$cyrstr = str_replace("%D0%AB", "Ы", $cyrstr);
	$cyrstr = str_replace("%D0%AA", "Ъ", $cyrstr);
	$cyrstr = str_replace("%D0%AD", "Э", $cyrstr);
	$cyrstr = str_replace("%D0%AE", "Ю", $cyrstr);
	$cyrstr = str_replace("%D0%AF", "Я", $cyrstr);

	$cyrstr = str_replace("%D0%B0", "а", $cyrstr);
	$cyrstr = str_replace("%D0%B1", "б", $cyrstr);
	$cyrstr = str_replace("%D0%B2", "в", $cyrstr);
	$cyrstr = str_replace("%D0%B3", "г", $cyrstr);
	$cyrstr = str_replace("%D0%B4", "д", $cyrstr);
	$cyrstr = str_replace("%D0%B5", "е", $cyrstr);
	$cyrstr = str_replace("%D1%91", "ё", $cyrstr);
	$cyrstr = str_replace("%D0%B6", "ж", $cyrstr);
	$cyrstr = str_replace("%D0%B7", "з", $cyrstr);
	$cyrstr = str_replace("%D0%B8", "и", $cyrstr);
	$cyrstr = str_replace("%D0%B9", "й", $cyrstr);
	$cyrstr = str_replace("%D0%BA", "к", $cyrstr);
	$cyrstr = str_replace("%D0%BB", "л", $cyrstr);
	$cyrstr = str_replace("%D0%BC", "м", $cyrstr);
	$cyrstr = str_replace("%D0%BD", "н", $cyrstr);
	$cyrstr = str_replace("%D0%BE", "о", $cyrstr);
	$cyrstr = str_replace("%D0%BF", "п", $cyrstr);
	$cyrstr = str_replace("%D1%80", "р", $cyrstr);
	$cyrstr = str_replace("%D1%81", "с", $cyrstr);
	$cyrstr = str_replace("%D1%82", "т", $cyrstr);
	$cyrstr = str_replace("%D1%83", "у", $cyrstr);
	$cyrstr = str_replace("%D1%84", "ф", $cyrstr);
	$cyrstr = str_replace("%D1%85", "х", $cyrstr);
	$cyrstr = str_replace("%D1%86", "ц", $cyrstr);
	$cyrstr = str_replace("%D1%87", "ч", $cyrstr);
	$cyrstr = str_replace("%D1%88", "ш", $cyrstr);
	$cyrstr = str_replace("%D1%89", "щ", $cyrstr);
	$cyrstr = str_replace("%D1%8C", "ь", $cyrstr);
	$cyrstr = str_replace("%D1%8B", "ы", $cyrstr);
	$cyrstr = str_replace("%D1%8A", "ъ", $cyrstr);
	$cyrstr = str_replace("%D1%8D", "э", $cyrstr);
	$cyrstr = str_replace("%D1%8E", "ю", $cyrstr);
	$cyrstr = str_replace("%D1%8F", "я", $cyrstr);

	return $cyrstr;
}
?>
